project:
  type: website
  output-dir: docs

website:
  title: "Site Moved"
  navbar:
    left:
      - text: "New Site"
        href: https://worldbank.github.io/geoPovLearn/

format:
  html:
    theme: cosmo
    toc: false
